### ISSUE TITLE
Display Translated Card Text 

### ISSUE THREAD

**Issue by natashaj7** [translation-cards/unhcr-deck#2]
Narrative
- As a Support Worker
- I want to display the translated text of a card
- So that in noisy environments I can still communicate my message

Context
- In areas where support workers are communicating with refugees, the environment can be busy and noisy making it difficult to hear the translated audio played by the app. This is why it would be helpful to also have the option of displaying the translated text along with the sound.

In Scope
- Allow workers to input text translation as third step to creating the app
- allow this step to be optional
- add icon for displaying text

Out of Scope
- generating automatic translation from text

Acceptance Criteria

1. Add Text Button
    GIVEN I am on the card menu
    WHEN I look the an individual card
    THEN I see an icon that has the classic T for text button

2. Display a language
    GIVEN I am on the card meny
    WHEN I click on the Text button
    THEN I see the translation in that language on the card
    AND an exit button on the far right

3. Returning from translated card
    GIVEN I am viewing the written translation
    WHEN I click the exit button on the card
    THEN I am taken back to the English side

4. Adding Written Translation
    GIVEN I choose the option to create a new card
    WHEN I complete the first two steps (writing the English phrase and recording the audio)
    THEN I get taken to a third optional step to write down the translation

**Comment by PatrickDale** [comment]
This issue was moved to translation-cards/translation-cards#2
