### ISSUE TITLE
Allowing grouping of translation decks

### ISSUE THREAD

**Issue by natashaj7** [translation-cards/unhcr-deck#3]
Narrative
- As a Support Worker
- I want to create groups of translation cards
- So that I can easily access and organize the translations I need in specific situations

Context
- There are many different situations and therefore sentences that need to be communicated between support workers and refugees in order to have effective communication. Workers need to be able to access specific sentences, quickly and easily. When the translation deck gets very long, having the ability to organize their decks is necessary to maintain quick and easy access to translations.

In Scope
- Create a new deck
- Add translations to that deck
- Have a general deck to add existing translations to

Out of Scope
- export a specific deck
- changing cards from one user group to another

Acceptance Criteria

1. Sidebar
GIVEN I am on the main menu
WHEN I click on the sidebar option in the top left corner
THEN then sidebar pops out display existing groups
AND the option to add a group

2. Add a new group
GIVEN I click on the sidebar
WHEN I click on the button to add a user group
THEN I am allowed to input the name of the user group

3. Adding cards to a user group
GIVEN I select a user group on the sidebar
WHEN I am taken to that user group
THEN the group name appears on the top
AND I am able to add cards to that group same as previously

4. Existing translation cards
GIVEN I already have cards in my application
WHEN I open the application
THEN a user group named 'General' is automatically created from the beginning
AND all my existing translation card are put into it

**Comment by natashaj7** [comment]
Narrative
- As a Support Worker
- I want to create groups of translation cards
- So that I can easily access and organize the translations I need in specific situations

Context
There are many different situations and therefore sentences that need to be communicated between support workers and refugees in order to have effective communication. Workers need to be able to access specific sentences, quickly and easily. When the translation deck gets very long, having the ability to organize their decks is necessary to maintain quick and easy access to translations.

In Scope
- Create a new deck
- add translations to that deck
- Have a general deck to add existing translations to

Out of Scope
- export a specific deck

Acceptance Criteria
    Add Text Button
    GIVEN I am on the card menu
    WHEN I look the an individual card
    THEN I see an icon that has the classic T for text button

    Display a language
    GIVEN I am on the card meny
    WHEN I click on the Text button
    THEN I see the translation in that language on the card
    AND an exit button on the far right

    Returning from translated card
    GIVEN I am viewing the written translation
    WHEN I click the exit button on the card
    THEN I am taken back to the English side

    Adding Written Translation
    GIVEN I choose the option to create a new card
    WHEN I complete the first two steps (writing the English phrase and recording the audio)
    THEN I get taken to a third optional step to write down the translation

**Comment by PatrickDale** [comment]
This issue was moved to translation-cards/translation-cards#3
